:sourcesdir: ../../../../source

[[integration_tests_mw]]
==== 中间件集成测试

中间件继承测试运行在具有完整功能的 Spring 容器里，而且可以连接数据库。在这些测试类里面，可以运行中间件里面各细分层的代码，比如从 ORM 层到 Service 层。

为了在测试中配置和启动中间件 Spring 容器，需要在项目中创建 `com.haulmont.cuba.testsupport.TestContainer` 的子类，并且在测试用例中使用其实例作为 JUnit Rule。

下面是容器类和<<quick_start>>中提到的 Sales 项目的一个集成测试的示例。所有的类必须在 `core` 模块的 `test` 目录。

[source, java]
----
include::{sourcesdir}/development/testing_3.java[]
----

自定义 `test-app.properties` 文件的示例：

[source, properties]
----
include::{sourcesdir}/development/testing_11.properties[]
----

推荐使用单独的测试数据库，可以通过 `build.gradle` 里面定义的 <<build.gradle_createDb, createDb>> 任务来创建：

[source, groovy]
----
include::{sourcesdir}/development/testing_4.groovy[]
----

这个测试容器应当在测试类里面作为 `@ClassRule` 注解指定的 JUnit 规则（rule）：
    
[source, java]
----
include::{sourcesdir}/development/testing_5.java[]
----

几个有用的测试容器方法::
+
--
`TestContainer` 类包含了以下几个方法，可以在测试类里面使用（参考上面的 `CustomerLoadTest` 例子）：

* `persistence()` – 返回 <<persistence,Persistence>> 接口的引用。

* `metadata()` – 返回 <<metadata,Metadata>> 接口的引用。

* `deleteRecord()` – 这一组重载方法的目的是在 `@After` 方法里面使用，在测试完成后清理数据库。
--

日志::
+
--
测试容器根据平台提供的 `test-logback.xml` 文件来配置日志。这个文件在 `cuba-core-tests` 工件的根目录。

可以通过以下方法配置测试的日志级别：

* 从平台的包里面拷贝 `test-logback.xml` 到项目 `core` 模块 `test` 根目录下，比如可以重命名为 `my-test-logback.xml`。

* 在 `my-test-logback.xml` 里面配置 appenders 和 loggers。

* 在测试容器里面添加一段静态初始化代码，这段代码通过设置 `logback.configurationFile` 这个系统属性来指定日志配置文件的位置：
+
[source, java]
----
include::{sourcesdir}/development/testing_9.java[]
----
--

[[integration_tests_mw_data_store]]
附加数据存储::
+
--
如果项目使用了<<data_store,附加数据存储>>，需要在测试容器里创建相应的 JDBC 数据源。比如，如果有名为 `mydb` 的数据存储，而且是 PostgreSQL 的数据库，则需要在测试容器中添加如下代码：

[source, java]
----
include::{sourcesdir}/development/testing_10.java[]
----

还有，如果额外的数据库类型跟主数据库不一致，需要在 `build.gradle` 的 `core` 模块将数据库的驱动添加到 `testRuntime` 依赖中。示例：

[source, java]
----
include::{sourcesdir}/development/testing_12.groovy[]
----
--

