:sourcesdir: ../../source

[appendix]
[[app_properties]]
== 应用程序属性

本节按字母顺序描述与报表生成器相关的应用程序属性。

[[reporting.backgroundReportProcessingTimeoutMs]]
reporting.backgroundReportProcessingTimeoutMs::
+
--
在 <<reporting.useBackgroundReportProcessing,reporting.useBackgroundReportProcessing>> 设置为 `true` 的情况下，用该参数定义报表执行过程超时的时限，单位为毫秒。

默认值: `10000`

保存在数据库

用于 *Middleware* block。
--

[[reporting.displayDeviceUnavailable]]
reporting.displayDeviceUnavailable::
+
--
允许在没有窗口界面的服务器操作系统中运行 OpenOffice/LibreOffice。

默认值: `false`

用于 *Middleware* block。
--

[[reporting.enableTabSymbolInDataSetEditor]]
reporting.enableTabSymbolInDataSetEditor::
+
--

定义是否应将 TAB 键作为 `\t` 符号处理，而不是在报表编辑界面的脚本字段中进行焦点切换。

默认值: `false`

用于客户端 block。
--

[[reporting.executionHistory.cleanup.days]]
reporting.executionHistory.cleanup.days::
+
--
计划任务会删除留存时间大于指定天数的所有<<execution_history,执行历史记录>>。如果该属性的值是 0，计划任务在删除记录时，不会考虑该值的设定。参阅 <<execution_history_cleanup, 清理历史记录>>了解设置计划任务的详情。

默认值： `730`

保存在数据库。

用于 *Middleware* block。

--

[[reporting.executionHistory.cleanup.itemsPerReport]]
reporting.executionHistory.cleanup.itemsPerReport::
+
--
计划任务会为每个报表保留不多于指定数量的<<execution_history,执行历史记录>>。不建议为该属性设置大于 1000 的值。如果该属性的值是 0，计划任务在删除记录时，不会考虑该值的设定。对于经常运行的报表，比如邮件模板、账单模板等，该参数很有用。参阅 <<execution_history_cleanup, 清理历史记录>>了解设置计划任务的详情。

默认值： `1000`

保存在数据库。

用于 *Middleware* block。
--

[[reporting.executionHistory.enabled]]
reporting.executionHistory.enabled::
+
--
启用 <<execution_history, 报表执行历史记录>> 的机制。

默认值： `false`

保存在数据库。

用于 *Middleware* block。

--

[[reporting.executionHistory.saveOutputDocument]]
reporting.executionHistory.saveOutputDocument::
+
--
如果设置为 true，并且 <<reporting.executionHistory.enabled,reporting.executionHistory.enabled>> 属性开启，报表结果文件会保存到 {main_man_url}/file_storage.html[文件存储]。参阅 <<history_output_documents,输出文档>> 了解详情。

默认值： `false`

保存在数据库。

用于 *Middleware* block。
--

[[reporting.fontsDir]]
reporting.fontsDir::
+
--
指定 HTML 转换为 PDF 时使用的字体目录的路径。

例如: `reporting.fontsDir = C:/Windows/Fonts`。

用于 *Middleware* block。
--

[[reporting.docFormatterTimeout]]
reporting.docFormatterTimeout::
+
--
设置 LibreOffice 转换 DOCX/XLSX 为 HTML/PDF 的超时时限，单位是秒。

当时间用完的时候，用户会收到一个错误消息。

默认值: `20`

用于 *Middleware* block。
--

[[reporting.openoffice.docx.useOfficeForDocumentConversion]]
reporting.openoffice.docx.useOfficeForDocumentConversion::
+
--
开启使用 OpenOffice 将含有 DOCX 模板的报表转换为 HTML/PDF 的功能，这样可以显著提高转换的准确性。

默认值: `false`

用于 *Middleware* block。
--

[[reporting.openoffice.path]]
reporting.openoffice.path::
+
--
设置 OpenOffice 的路径。

默认值: `/`

用于 *Middleware* block。
--

[[reporting.openoffice.ports]]
reporting.openoffice.ports::
+
--
为 OpenOffice/LibreOffice 指定用逗号或竖直分隔符隔开的可用端口列表。

例如: `reporting.openoffice.ports = 8100|8101|8102|8103|8104|8105`.

默认值: `8100, 8101, 8102, 8103`.

用于 *Middleware* block。
--

[[reporting.putEmptyRowIfNoDataSelected]]
reporting.putEmptyRowIfNoDataSelected::
+
--
设置当报表带区的数据集没有返回记录时是否仍然将带区显示一次。

默认值: `true`

用于 *Middleware* block。
--

[[reporting.useBackgroundReportProcessing]]
reporting.useBackgroundReportProcessing::
+
--
允许在后台运行报表执行程序。该属性是为了实现<<run_cancel,取消>>操作选项。

默认值: `false`

保存在数据库

用于 *Middleware* block。
--
